### ISSUE TITLE
Make Lance work with pyarrow.write_dataset API

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#122]
# Problem Statement

With pyarrow's `write_dataset`, the arrow can take care of partition, chunk size and etc.

https://arrow.apache.org/docs/python/generated/pyarrow.dataset.write_dataset.html#pyarrow.dataset.write_dataset

Currently, if we run 

```
    format = lance.LanceFileFormat()
    ds.write_dataset(
        tbl,
        "dir",
        partitioning=["split"],
        format=format,
        file_options=format.make_write_options(),
    )
```

which reports error:

```
Traceback (most recent call last):
  File "/home/lei/work/sophon/tools/datasets/./bdd100k.py", line 88, in <module>
    data_gen()
  File "/home/lei/work/lance/python/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lei/work/lance/python/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lei/work/lance/python/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lei/work/lance/python/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lei/work/sophon/tools/datasets/./bdd100k.py", line 82, in data_gen
    file_options=lance.LanceFileFormat().make_write_options(),
  File "pyarrow/_dataset.pyx", line 826, in pyarrow._dataset.FileFormat.make_write_options
  File "pyarrow/_dataset.pyx", line 724, in pyarrow._dataset.FileWriteOptions.wrap
TypeError: lance
```

As seen here: https://github.com/apache/arrow/blob/fa33ca400759d4e9912b06df6680bf0199e28fd5/python/pyarrow/_dataset.pyx#L713-L728

# Desired Behavior

Lance can work well with `pyarrow.dataset.write_dataset()` and writes partitioned dataset.

**Comment by changhiskhan** [comment]
The problem is that FileFormat has a hard-coded list of FileFormat’s it supports. https://github.com/apache/arrow/blob/fa33ca400759d4e9912b06df6680bf0199e28fd5/python/pyarrow/_dataset.pyx#L748
So this needs to be done by Arrow.

**Comment by eddyxu** [comment]
We already implement a `LanceFormat`, it is possible that if we implement [`LanceFileFormat::make_write_options()`](https://github.com/apache/arrow/blob/fa33ca400759d4e9912b06df6680bf0199e28fd5/python/pyarrow/_dataset.pyx#L825-L826) , we can by pass the `FileWriteOptions.wrap()`, as shown in the stack.

**Comment by changhiskhan** [comment]
ic. yeah, we'd also have to create a subclass of FileWriteOptions to avoid the call to FileFormat.wrap: https://github.com/apache/arrow/blob/fa33ca400759d4e9912b06df6680bf0199e28fd5/python/pyarrow/_dataset.pyx#L731

**Comment by changhiskhan** [comment]
as an aside, I do wonder if we can monkey patch pyarrow in the short term so we get arrow to automatically recognize a call like

```
import pyarrow.dataset as ds
dataset = ds.dataset("path.lance")
```
