### ISSUE TITLE
Segfault in Python with extension type

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#235]
# Problem Statement

```python

uri = "s3://eto-public/datasets/oxford_pet/oxford_pet.lance"
ds = lance.dataset(uri)

print(duckdb.query("""
        SELECT _pk FROM ds WHERE class = 'pug' LIMIT 20
"""))
```

```
(gdb) bt
#0  0x0000555555786650 in ?? ()
#1  0x00005555557a4d82 in PyGILState_Ensure ()
#2  0x00007fffa8cd9481 in arrow::py::PyExtensionType::~PyExtensionType() ()
   from /home/lei/work/lance/python/venv/lib/python3.10/site-packages/pyarrow/libarrow_python.so.900
#3  0x00007fffa92f2c4a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
   from /home/lei/work/lance/python/venv/lib/python3.10/site-packages/pyarrow/libarrow.so.900
#4  0x00007fffa9ec34e2 in arrow::Field::~Field() () from /home/lei/work/lance/python/venv/lib/python3.10/site-packages/pyarrow/libarrow.so.900
#5  0x00007fffaba3ec0a in std::vector<std::shared_ptr<arrow::Field>, std::allocator<std::shared_ptr<arrow::Field> > >::~vector() ()
   from /home/lei/work/lance/python/venv/lib/python3.10/site-packages/pyarrow/lib.cpython-310-x86_64-linux-gnu.so
#6  0x00007fffa9ec7477 in arrow::Schema::~Schema() () from /home/lei/work/lance/python/venv/lib/python3.10/site-packages/pyarrow/libarrow.so.900
#7  0x00007fffa70ef23a in std::_Sp_counted_ptr_inplace<arrow::dataset::ScanOptions, std::allocator<arrow::dataset::ScanOptions>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
    () from /home/lei/work/lance/python/venv/lib/python3.10/site-packages/pyarrow/_dataset.cpython-310-x86_64-linux-gnu.so
```

**Comment by eddyxu** [comment]
It is weird that such crash does not happen in python shell.

```python

>>> import duckdb
>>> import lance
>>> uri = "s3://eto-public/datasets/oxford_pet/oxford_pet.lance"
>>> ds = lance.dataset(uri)
>>> print(duckdb.query("""
...         SELECT _pk FROM ds WHERE class = 'pug' LIMIT 20
... """))
>>> exit()
```
