### ISSUE TITLE
Panic when creating index

### ISSUE THREAD

**Issue by cemoody** [eto-ai/lance#573]
Hi folks! I've got a panic when creating a new index. Here's a Google Colab link with a minimal repro in case that's easier than the script below:

[link](https://gist.github.com/cemoody/5413c9d7628e246d53e45de07ee07aef)

```
import lance
import pyarrow as pa
import numpy as np
import pandas as pd
from loguru import logger

     

n = 1_000
pid = np.arange(0, n).astype(np.uint64)

arr = np.random.randn(n, 768).astype(np.float32)
arr = np.ravel(arr).copy()
     

!rm -rdf 0.lance
     

schema = pa.schema(
    [
        pa.field("id", pa.uint64(), False),
        pa.field("vector", pa.list_(pa.float32(), 768), True),
    ]
)

table = pa.Table.from_arrays(
    [
        pa.array(pid, type=pa.uint64()),
        pa.FixedSizeListArray.from_arrays(
            pa.array(arr, type=pa.float32()), list_size=768
        ),
    ],
    schema=schema,
)

lance.write_dataset(
    table,
    "0.lance",
)


dataset = lance.dataset("0.lance")
logger.info(f"Creating index")
dataset.create_index(
    "vector",
    index_type="IVF_PQ",
    num_partitions=64,
    num_sub_vectors=16,
)
     
```

Which gives me the following errors:

```
2023-02-13 23:46:33.892 | INFO     | __main__:<module>:25 - Creating index
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-5-aa15cb964f53> in <module>
     24 dataset = lance.dataset("0.lance")
     25 logger.info(f"Creating index")
---> 26 dataset.create_index(
     27     "vector",
     28     index_type="IVF_PQ",

/usr/local/lib/python3.8/dist-packages/lance/dataset.py in create_index(self, column, index_type, name, **kwargs)
    282         if isinstance(column, str):
    283             column = [column]
--> 284         self._ds.create_index(column, index_type, name, kwargs)
    285 
    286 

PanicException: called `Result::unwrap()` on an `Err` value: IO("task 313 panicked")
```

**Comment by cemoody** [comment]
I'm also investigating another spurious error which may be related:

There's not a lot of datapoints. Perhaps it is caused by a k-means cluster with zero points?

```
Building vector index: IVF64,PQ16
thread 'thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: DivideByZero', /home/runner/work/lance/lance/rust/src/utils/kmeans.rs:tokio-runtime-worker185' panicked at ':called `Result::unwrap()` on an `Err` value: DivideByZero48', 
/home/runner/work/lance/lance/rust/src/utils/kmeans.rsnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
:185:48
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IO("task 118 panicked")', /home/runner/work/lance/lance/rust/src/utils/kmeans.rs:275:67
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 324, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 397, in call_function_sync
    res = fun(*args, **kwargs)
  File "/root/test_lance_index.py", line 122, in lance_single
    dataset.create_index(
  File "/usr/local/lib/python3.9/site-packages/lance/dataset.py", line 284, in create_index
    self._ds.create_index(column, index_type, name, kwargs)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: IO("task 118 panicked")
```

**Comment by eddyxu** [comment]
Thanks @cemoody for reporting! Yes, it seems to be a `DivideByZero` exception

```
python/lance/dataset.py:284: PanicException
----------------------------------------------- Captured stdout call -----------------------------------------------
Building vector index: IVF64,PQ16
----------------------------------------------- Captured stderr call -----------------------------------------------
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: DivideByZero', /Users/lei/work/lance/rust/src/utils/kmeans.rs:185:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IO("task 251 panicked")', /Users/lei/work/lance/rust/src/utils/kmeans.rs:275:67
```

Working on a fix now.

**Comment by changhiskhan** [comment]
slight tangent: @cemoody would you find #574 useful? lmk if you have any feedback on the API. Thanks!

**Comment by cemoody** [comment]
#574 would've been a little helpful; not a big deal. But good for me to be aware of that for next time
